Home 04
valed-dm/base-python-homeworks pull request #4
Opened 2023-02-22 08:23 UTC by valed-dm

Локальный и Git тесты пройдены.

2023-02-26 14:20 UTC, mahenzon commented on homework_04/jsonplaceholder_requests.py
> +    print(f"{'UID:' : <6}{'user:' : <30}{'username:' : <20}{'email:' : <50}")
лучше воспользоваться библиотекой logging, чем делать через print

2023-02-26 14:22 UTC, mahenzon commented on homework_04/models.py
> +class Base:
круто что создан базовый класс

2023-02-26 14:26 UTC, mahenzon commented on homework_04/pyproject.toml
> +python-dotenv = "^0.21.1"
к сожалению, тесты не прошли, так как этот модуль не был установлен


```
SKIPPED [1] testing/test_homework_04/test_main.py:4: could not import 'homework_04': No module named 'dotenv'
```

самый простой способ тут это добавить рядом файл `requirements.txt`

https://python-poetry.org/docs/cli/#export

```shell
poetry export -f requirements.txt --output requirements.txt
```
чтобы зависимости были установлены перед тестами
https://github.com/valed-dm/base-python-homeworks/blob/main/.github/workflows/run_tests.yml#L38-L47

2023-02-26 14:26 UTC, mahenzon requested changes
Отличная работа. Верну на доработку только потому, что зависимости не были установлены, и поэтому тесты не прошли

2023-02-28 09:28 UTC, valed-dm commented on homework_04/jsonplaceholder_requests.py
> +    print(f"{'UID:' : <6}{'user:' : <30}{'username:' : <20}{'email:' : <50}")
заменил print() на log.info()

2023-02-28 16:09 UTC, valed-dm commented on homework_04/pyproject.toml
> +python-dotenv = "^0.21.1"
Экспортировал requirements.txt из poetry.
Добавил дефолтные значения users, posts urls чтобы успешно пройти тест на github в отсутствие .env-файла.

2023-02-28 19:11 UTC, mahenzon approved these changes
Отличная работа!

2023-02-28 19:18 UTC, merged